# we're exploiting the promise that there's "at least one version of Ruby available"...
# test spec. updated for the MongoDB extension and php7 support
language: php

php:
# - 5.6
 - 7.0

env:
# - GENGHIS_BACKEND=ruby
 - GENGHIS_BACKEND=php
# - GENGHIS_BACKEND=php MONGO_PHP_VERSION=1.2.8
 - GENGHIS_BACKEND=php MONGO_PHP_VERSION=1.2.9

matrix:
  exclude:
    - php: 7.0
      env: GENGHIS_BACKEND=ruby

services: mongodb

before_script:
 - 'sh -c "if [ ! -z $MONGO_PHP_VERSION ]; then pecl install -f mongodb-${MONGO_PHP_VERSION}; fi"'

before_install:
 - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: bundle install --without development

# wheee!
script: rspec
